<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TicketSystem.Domain\TicketSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Comments\Queries\" />
    <Folder Include="Tickets\Commands\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
